// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MysqlOmdbRepository is an autogenerated mock type for the MysqlOmdbRepository type
type MysqlOmdbRepository struct {
	mock.Mock
}

// LogRequest provides a mock function with given fields: ctx, request, response
func (_m *MysqlOmdbRepository) LogRequest(ctx context.Context, request string, response string) (int64, error) {
	ret := _m.Called(ctx, request, response)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, request, response)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, request, response)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
