kind: pipeline
type: docker
name: default
steps:
- name: test
  image: golang
  environment:
    COVERALLS_TOKEN:
      from_secret: COVERALLS_TOKEN
  commands:
  - make test
  - go get github.com/mattn/goveralls
  - goveralls -service drone.io