kind: pipeline
type: docker
name: default
steps:
- name: test
  image: golang:alpine
  commands:
  - go test -v -cover -covermode=atomic ./...

- name: coveralls
  image: lizheming/drone-coveralls
  settings:
    token:
      from_secret: coveralls_token
    files:
    - ./coverage.out