kind: pipeline
type: docker
name: default
steps:
- name: test
  image: golang
  commands:
  - go get github.com/mattn/goveralls
  - goveralls -v -service drone.io
  environment:
    COVERALLS_TOKEN:
      from_secret: coveralls_token