kind: pipeline
type: docker
name: default
steps:
- name: test
  image: golang
  commands:
  - make test

- name: coveralls
  image: lizheming/drone-coveralls
  settings:
    token:
      from_secret: coveralls_token
    files:
    - ./coverage.out