version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    container_name: movie-app
    ports:
      - 5050:5050
    depends_on:
      - mysql
    restart: always
  
  mysql:
    image: mysql:8.0
    container_name: movie-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d